name: Build & Tests

on:
    push:
        branches:
            - main
        paths-ignore:
            - "**.md"
            - "docs/**"
    pull_request:
        paths-ignore:
            - "**.md"
            - "docs/**"

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest] # not supported windows-latest, macOS-latest
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'npm'
            - run: npm ci --legacy-peer-deps
            - name: Prettier Format Check
              run: npm run format-check
            - name: ESLint Check
              run: npm run lint
            - name: Build & Test
              run: npm run test

    # End to end save and restore
    test-save:
        strategy:
            matrix:
                os: [ubuntu-latest] # not supported windows-latest, macOS-latest
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Vulnerability scan
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: "fs"
                  ignore-unfixed: true
                  cache-dir: .trivy
            - run: ls -laR .trivy
            - name: Save cache
              uses: ./
              with:
                  gh-token: ${{ secrets.GITHUB_TOKEN }}
                  prefix: ${{ matrix.os }}

    test-restore:
        needs: test-save
        strategy:
            matrix:
                os: [ubuntu-latest] # not supported windows-latest, macOS-latest
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Restore cache
              uses: ./
              with:
                  gh-token: ${{ secrets.GITHUB_TOKEN }}
                  prefix: ${{ matrix.os }}
            - run: ls -laR .trivy
            - name: Verify cache files in working directory
              shell: bash
              run: __tests__/verify-cache-files.sh .trivy
